function build_simulink_model()
% BUILD_SIMULINK_MODEL  程序化搭建 motor_algo_sim.slx 并跑通验证
%
% 与 .m 逐拍模型(sim_run_side)互为交叉验证:同样的控制律、被控对象和
% 编码器链代码(由 motor_params() 的数值烘焙成模块代码),在 Simulink 里
% 以 1 kHz 离散步长重跑"阶跃 500"场景,对比峰值/稳态。
%
% 需要 Simulink 许可证。重复运行会先关闭并删除旧模型再重建。

here = fileparts(mfilename('fullpath'));
addpath(fullfile(here, 'fw'));
P = motor_params();
mdl = 'motor_algo_sim';

if bdIsLoaded(mdl), close_system(mdl, 0); end
if exist(fullfile(here, [mdl '.slx']), 'file')
    delete(fullfile(here, [mdl '.slx']));
end
new_system(mdl);
set_param(mdl, 'SolverType', 'Fixed-step', 'Solver', 'FixedStepDiscrete', ...
          'FixedStep', num2str(P.Ts), 'StopTime', '3');

%% ---- 模块代码(由参数烘焙,保证与 .m 模型同源) ----------------------------
algoCode = sprintf([ ...
'function [duty, target, integDbg] = fw_algo(cmd, measPct, measOk)\n' ...
'%%#codegen\n' ...
'persistent integ targetState init\n' ...
'if isempty(init)\n' ...
'    init = 1; integ = single(0); targetState = int16(0);\n' ...
'end\n' ...
'd = int16(cmd) - targetState;\n' ...
'if d > int16(%d), d = int16(%d); end\n' ...
'if d < int16(-%d), d = int16(-%d); end\n' ...
'targetState = targetState + d;\n' ...
'target = double(targetState);\n' ...
'if ~measOk\n' ...
'    integ = single(0);\n' ...
'    duty = double(targetState);\n' ...
'    integDbg = double(integ);\n' ...
'    return\n' ...
'end\n' ...
'e = single(targetState) - single(measPct);\n' ...
'if (e > single(%d)) || (e < single(-%d))\n' ...
'    integ = integ + single(%.6g) * e;\n' ...
'    if integ > single(%d), integ = single(%d); end\n' ...
'    if integ < single(-%d), integ = single(-%d); end\n' ...
'end\n' ...
'u = (single(%.6g) * single(targetState)) + (single(%.6g) * e) + integ;\n' ...
'if u > single(%d), u = single(%d); end\n' ...
'if u < single(-%d), u = single(-%d); end\n' ...
'if (u < single(%d)) && (u > single(-%d))\n' ...
'    duty = 0;\n' ...
'    integDbg = double(integ);\n' ...
'    return\n' ...
'end\n' ...
'duty = double(fix(u));\n' ...
'integDbg = double(integ);\n' ...
'end\n'], ...
P.maxStep, P.maxStep, P.maxStep, P.maxStep, ...
P.eDeadband, P.eDeadband, double(P.servoKi), P.integMax, P.integMax, ...
P.integMax, P.integMax, double(P.servoFf), double(P.servoKp), ...
P.outMax, P.outMax, P.outMax, P.outMax, P.outDeadband, P.outDeadband);

plantCode = sprintf([ ...
'function [countDelta, vTrue, iDbg] = fw_plant(duty, tauLoad)\n' ...
'%%#codegen\n' ...
'persistent x phi count init\n' ...
'if isempty(init)\n' ...
'    init = 1; x = [0; 0]; phi = 0; count = 0;\n' ...
'end\n' ...
'Ad = [%.17g %.17g; %.17g %.17g];\n' ...
'Bd = [%.17g %.17g; %.17g %.17g];\n' ...
'd = min(max(duty, -1000), 1000);\n' ...
'V = d / 1000 * %.6g;\n' ...
'x = Ad * x + Bd * [V; -tauLoad];\n' ...
'tauC = %.6g; J = %.17g; thresh = %.6g; Kt = %.17g;\n' ...
'w = x(2);\n' ...
'if abs(w) > thresh\n' ...
'    dOm = sign(w) * tauC / J * %.6g;\n' ...
'    if abs(dOm) > abs(w)\n' ...
'        w = 0;\n' ...
'    else\n' ...
'        w = w - dOm;\n' ...
'    end\n' ...
'else\n' ...
'    if abs(Kt * x(1) - tauLoad) <= tauC\n' ...
'        w = 0;\n' ...
'    end\n' ...
'end\n' ...
'x(2) = w;\n' ...
'omegaWheel = w / %.17g;\n' ...
'phi = phi + omegaWheel * %.6g;\n' ...
'c = floor(phi * %.17g / (2 * pi) * %d);\n' ...
'countDelta = c - count;\n' ...
'count = c;\n' ...
'vTrue = omegaWheel * %.17g * 1000;\n' ...
'iDbg = x(1);\n' ...
'end\n'], ...
P.Ad(1,1), P.Ad(1,2), P.Ad(2,1), P.Ad(2,2), ...
P.Bd(1,1), P.Bd(1,2), P.Bd(2,1), P.Bd(2,2), ...
P.Vnom, P.tauC, P.J, P.omegaThresh, P.Kt, P.Ts, ...
P.gearRatio, P.Ts, P.gearRatio, P.encPpr * 4, P.wheelR_m);

encCode = sprintf([ ...
'function [measPctL, alive] = fw_enc(dSide)\n' ...
'%%#codegen\n' ...
'persistent win idx winFull lastMove speedMmS first init\n' ...
'if isempty(init)\n' ...
'    init = 1; win = zeros(2, %d); idx = 0; winFull = false;\n' ...
'    lastMove = 0; speedMmS = [0 0]; first = true;\n' ...
'end\n' ...
'dl = dSide; dr = 0;\n' ...
'if (dl ~= 0) || (dr ~= 0), lastMove = tick(); end\n' ...
'alive = (tick() - lastMove) < %d;\n' ...
'if first, first = false; lastMove = tick(); alive = true; end\n' ...
'idx = idx + 1; win(1, idx) = dl; win(2, idx) = dr;\n' ...
'if idx == %d, idx = 0; winFull = true; end\n' ...
'n = %d * double(winFull) + idx * ~winFull;\n' ...
'if n > 0\n' ...
'    cpwr = single(%d);\n' ...
'    circMm = single(3.14159265) * single(%d);\n' ...
'    meanL = single(sum(win(1, 1:n))) / single(n);\n' ...
'    meanR = single(sum(win(2, 1:n))) / single(n);\n' ...
'    mmPerS = (meanL * single(1000) / cpwr) * circMm;\n' ...
'    speedMmS(1) = fix(double(mmPerS));\n' ...
'    mmPerS = (meanR * single(1000) / cpwr) * circMm;\n' ...
'    speedMmS(2) = fix(double(mmPerS));\n' ...
'end\n' ...
'measPctL = fix(speedMmS(1) * 1000 / %d);\n' ...
'measPctL = min(max(measPctL, -1000), 1000);\n' ...
'end\n' ...
'function t = tick()\n' ...
'%% 与 .tk 域一致:1 ms 一拍\n' ...
'persistent k init2\n' ...
'if isempty(init2), init2 = 1; k = 0; end\n' ...
'k = k + 1;\n' ...
't = k;\n' ...
'end\n'], ...
P.windowMs, P.aliveWindowMs, P.windowMs, P.windowMs, ...
2 * P.countsWheelRev, P.wheelDiaMm, P.fullScaleMmS);

%% ---- 搭模型 ---------------------------------------------------------------
add_block('simulink/Sources/Step', [mdl '/Cmd'], ...
          'Time', '0.3', 'Before', '0', 'After', '500', ...
          'Position', [40 100 70 130]);
add_block('simulink/User-Defined Functions/MATLAB Function', [mdl '/FW MotorAlgo'], ...
          'Position', [220 90 360 170]);
add_block('simulink/User-Defined Functions/MATLAB Function', [mdl '/FW Plant'], ...
          'Position', [470 90 610 170]);
add_block('simulink/User-Defined Functions/MATLAB Function', [mdl '/FW Encoder'], ...
          'Position', [700 90 840 170]);
add_block('simulink/Sources/Constant', [mdl '/TauLoad'], ...
          'Value', '0', 'Position', [400 200 430 230]);
add_block('simulink/Sources/Constant', [mdl '/ClosedLoop'], ...
          'Value', '1', 'Position', [40 210 70 240]);
add_block('simulink/Logic and Bit Operations/Logical Operator', [mdl '/AND'], ...
          'Operator', 'AND', 'Inputs', '2', 'Position', [120 190 150 230]);
add_block('simulink/Math Operations/Gain', [mdl '/SideSum'], ...
          'Gain', '2', 'Position', [880 105 910 135]);
% 固件时序里编码器在第 k 拍消费的是上一拍累计的计数增量(MOTOR_setSpeed
% 的作用落在本拍区间),所以反馈回路里显式放一拍延迟,同时打破代数环。
add_block('simulink/Discrete/Unit Delay', [mdl '/CntDelay'], ...
          'SampleTime', num2str(P.Ts), 'InitialCondition', '0', ...
          'Position', [930 105 960 135]);
add_block('simulink/Sinks/To Workspace', [mdl '/twTarget'], 'VariableName', 'twTarget', ...
          'SaveFormat', 'Timeseries', 'Position', [470 260 540 290]);
add_block('simulink/Sinks/To Workspace', [mdl '/twDuty'], 'VariableName', 'twDuty', ...
          'SaveFormat', 'Timeseries', 'Position', [470 310 540 340]);
add_block('simulink/Sinks/To Workspace', [mdl '/twMeas'], 'VariableName', 'twMeas', ...
          'SaveFormat', 'Timeseries', 'Position', [960 260 1030 290]);
add_block('simulink/Sinks/To Workspace', [mdl '/twV'], 'VariableName', 'twV', ...
          'SaveFormat', 'Timeseries', 'Position', [960 320 1030 350]);

set_chart_script([mdl '/FW MotorAlgo'], algoCode, P.Ts);
set_chart_script([mdl '/FW Plant'],     plantCode, P.Ts);
set_chart_script([mdl '/FW Encoder'],   encCode,   P.Ts);

add_line(mdl, 'Cmd/1', 'FW MotorAlgo/1', 'autorouting', 'on');
add_line(mdl, 'FW Encoder/1', 'FW MotorAlgo/2', 'autorouting', 'on');
add_line(mdl, 'AND/1', 'FW MotorAlgo/3', 'autorouting', 'on');
add_line(mdl, 'ClosedLoop/1', 'AND/1', 'autorouting', 'on');
add_line(mdl, 'FW Encoder/2', 'AND/2', 'autorouting', 'on');
add_line(mdl, 'FW MotorAlgo/1', 'FW Plant/1', 'autorouting', 'on');
add_line(mdl, 'TauLoad/1', 'FW Plant/2', 'autorouting', 'on');
add_line(mdl, 'FW Plant/1', 'SideSum/1', 'autorouting', 'on');
add_line(mdl, 'SideSum/1', 'CntDelay/1', 'autorouting', 'on');
add_line(mdl, 'CntDelay/1', 'FW Encoder/1', 'autorouting', 'on');
add_line(mdl, 'FW MotorAlgo/2', 'twTarget/1', 'autorouting', 'on');
add_line(mdl, 'FW MotorAlgo/1', 'twDuty/1', 'autorouting', 'on');
add_line(mdl, 'FW Encoder/1', 'twMeas/1', 'autorouting', 'on');
add_line(mdl, 'FW Plant/2', 'twV/1', 'autorouting', 'on');

%% ---- 运行验证:与 .m 模型对比 ---------------------------------------------
save_system(mdl, fullfile(here, [mdl '.slx']));
out = sim(mdl);

Lm = sim_run_side(P, [zeros(1, 300), 500 * ones(1, 2700)]);   % 同场景 .m 模型
vSlk = out.twV.Data;
vM   = Lm.vTrue;
pkSlk = max(vSlk(301:end));   pkM = max(vM(301:end));
ssSlk = mean(vSlk(2600:end)); ssM = mean(vM(2600:end));
fprintf('== Simulink vs .m 模型(阶跃 500,同参数)==\n');
fprintf('   Simulink: 峰值 %.1f mm/s,稳态 %.1f mm/s\n', pkSlk, ssSlk);
fprintf('   .m 模型 : 峰值 %.1f mm/s,稳态 %.1f mm/s\n', pkM, ssM);
chk = abs(pkSlk - pkM) < 20 && abs(ssSlk - ssM) < 10;
if chk, chkTxt = '一致'; else, chkTxt = '不一致'; end
fprintf('   %s(峰值差 %.1f mm/s,稳态差 %.1f mm/s)\n', ...
        chkTxt, abs(pkSlk - pkM), abs(ssSlk - ssM));
assert(chk, 'Simulink 与 .m 模型结果差异过大');

fig = figure('Visible', 'off', 'Position', [0 0 1280 480], 'Color', 'w');
tiledlayout(fig, 1, 2, 'TileSpacing', 'compact', 'Padding', 'compact');
nexttile; hold on;
plot(Lm.t * 1000, Lm.vTrue, 'b', 'LineWidth', 1.2);
plot(vSlk, 'r--', 'LineWidth', 1);
grid on; xlabel('t [ms]'); ylabel('true wheel speed [mm/s]');
legend('.m step model', 'Simulink model', 'Location', 'southeast');
title('cross-check: step 500, closed loop');
nexttile; hold on;
plot(out.twDuty.Data, 'b', 'LineWidth', 1);
plot(out.twMeas.Data, 'm', 'LineWidth', 1);
grid on; xlabel('t [ms]'); ylabel('duty / meas [pct*10]');
legend('duty', 'measured pct*10', 'Location', 'southeast');
exportgraphics(fig, fullfile(here, P.figDir, 'i_simulink_crosscheck.png'), 'Resolution', 150);
fprintf('图已输出到 %s/i_simulink_crosscheck.png;模型已保存为 %s.slx\n', P.figDir, mdl);
end

function set_chart_script(blkPath, code, Ts)
rt = sfroot;
ch = rt.find('-isa', 'Stateflow.EMChart', 'Path', blkPath);
assert(~isempty(ch), '找不到 MATLAB Function 图:%s', blkPath);
ch.Script = code;
ch.ChartUpdate = 'DISCRETE';
ch.SampleTime = num2str(Ts);
end
