/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxPort.h"
#include "uart.h"
#include "motor.h"
#include "esp8266.h"
#include "protocol.h"
#include "robot.h"

#if defined(__TASKING__)
#include "FreeRTOS.h"
#include "task.h"
#endif

IfxCpu_syncEvent cpuSyncEvent = 0;

#define LED1_PIN_INDEX 5  /* LED1 on KIT_AURIX_TC275_LITE, Port 0 Pin 5 */
#define BLINKY_PERIOD  250U

#if defined(__TASKING__)
static void vBlinkyTask(void *pvParameters)
{
    while (1)
    {
        IfxPort_setPinState(&MODULE_P00, LED1_PIN_INDEX, IfxPort_State_toggled);
        vTaskDelay(pdMS_TO_TICKS(BLINKY_PERIOD));
    }
}

/* Loopback echo test: any byte received on ASCLIN0 RX is echoed back on TX.
 * Type a character in the terminal; if it comes back, the whole USB-UART
 * path (P14.1 <-> FT2232 <-> COM port) works. */
static void vUartEchoTask(void *pvParameters)
{
    while (1)
    {
        UART_echoTask();
    }
}

/* Robot control task: 10 ms loop for safety checks and motion execution.
 * HTTP mode reports status through /api/status instead of injecting binary
 * status frames into the browser TCP stream. */
static void vRobotControlTask(void *pvParameters)
{
    (void)pvParameters;

    while (1)
    {
        ROBOT_task();

        vTaskDelay(pdMS_TO_TICKS(10));
    }
}
#endif

void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

#if defined(__TASKING__)
    /* Initialize UART for serial printing */
    UART_init();
    UART_println("UART initialized");


    /* Configure LED1 as push-pull output */
    IfxPort_setPinMode(&MODULE_P00, LED1_PIN_INDEX, IfxPort_Mode_outputPushPullGeneral);

    /* Create the LED blinky task */
    xTaskCreate(vBlinkyTask, "blinky", configMINIMAL_STACK_SIZE, NULL, 1, NULL);

    /* Create the loopback echo test task */
    xTaskCreate(vUartEchoTask, "echo", configMINIMAL_STACK_SIZE, NULL, 1, NULL);

    /* Initialize the TB6612 motor drivers (4 channels, 2x TB6612) */
    MOTOR_init();

    /* Initialize the binary protocol parser */
    PROTO_init();

    /* Initialize the robot state machine / motion controller */
    ROBOT_init();

    /* Create the robot control task (10 ms safety + status upload) */
    xTaskCreate(vRobotControlTask, "robot", configMINIMAL_STACK_SIZE * 2, NULL, 2, NULL);

    /* Initialize the ESP8266 WiFi module on ASCLIN1 (P15.0 TX / P15.1 RX) */
    ESP8266_init();

    /* Create the ESP8266 task (AP mode + TCP bridge) */
    xTaskCreate(ESP8266_task, "esp8266", configMINIMAL_STACK_SIZE * 4, NULL, 1, NULL);


    /* Start the FreeRTOS scheduler */
    vTaskStartScheduler();
#endif
        
    while(1)
    {
    }
}

#if defined(__TASKING__)
void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName)
{
    while (1)
    {
        __nop();
    }
}
#endif
