/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
/* CPU0 - FreeRTOS core: robot control task (safety checks + command
 * execution + status publishing), console UART, LED. The motor algorithm
 * runs on CPU1 and the ESP32-C6 WiFi link on CPU2 (see Cpu1/Cpu2_Main.c). */
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxPort.h"
#include "bsp/stime.h"
#include "bsp/uart.h"
#include "bsp/wdg.h"
#include "mw/calib/calib_store.h"
#include "mw/xcore/xcore.h"
#include "mw/proto/protocol.h"
#include "mw/app_version.h"
#include "app/robot.h"

#if defined(__TASKING__)
#include "FreeRTOS.h"
#include "task.h"
#endif

IfxCpu_syncEvent cpuSyncEvent = 0;

#define LED1_PIN_INDEX 5  /* LED1 on KIT_AURIX_TC275_LITE, Port 0 Pin 5 */
#define BLINKY_PERIOD  250U

#if defined(__TASKING__)
static void vBlinkyTask(void *pvParameters)
{
    while (1)
    {
        IfxPort_setPinState(&MODULE_P00, LED1_PIN_INDEX, IfxPort_State_toggled);
        vTaskDelay(pdMS_TO_TICKS(BLINKY_PERIOD));
    }
}

/* Loopback echo test: any byte received on ASCLIN0 RX is echoed back on TX.
 * Type a character in the terminal; if it comes back, the whole USB-UART
 * path (P14.1 <-> FT2232 <-> COM port) works. */
static void vUartEchoTask(void *pvParameters)
{
    while (1)
    {
        UART_echoTask();
    }
}

/* Robot control task (10 ms): drain the command queue filled by CPU2 (WiFi),
 * run the safety state machine, publish the robot status for CPU2's replies
 * and forward the side speed targets to the CPU1 motor algorithm. Also
 * drains the cross-core log ring to the console UART. */
static void vRobotControlTask(void *pvParameters)
{
    (void)pvParameters;

    while (1)
    {
        WDG_serviceCpu();     /* CPU0 WDT feed point, 10 ms (vTaskDelay below) */

        XcoreCmdMsg msg;

        while (XCORE_cmdPop(&msg))
        {
            PROTO_handleCommand(msg.cmd, msg.data, msg.len);
        }

        ROBOT_task();

        /* DPT result mailbox + deferred calibration saves (doc 34 SS8.3).
         * A save masks this core's interrupts for tens of ms; the 10 ms feed
         * above and the one below bound the gap well inside the ~0.5 s CPU
         * watchdog window. */
        CALIB_tick();
        WDG_serviceCpu();

        {
            ProtocolStatus status;
            RobotSpeeds    speeds = ROBOT_getSpeeds();

            status.state         = ROBOT_getState();
            status.leftSpeed     = speeds.left;
            status.rightSpeed    = speeds.right;
            status.heartbeatOk   = ROBOT_isHeartbeatOk() ? 1 : 0;
            status.faultCode     = ROBOT_getFaultCode();
            status.emergencyStop = ROBOT_isEmergencyStop() ? 1 : 0;

            /* Measured wheel speed replaces the commanded echo once the Hall
             * encoders report activity; until then the old behavior holds. */
            {
                XcoreEncoder enc;

                XCORE_encoderRead(&enc);
                if (enc.alive)
                {
                    status.leftSpeed  = (sint8)(enc.pctLeft / 10);
                    status.rightSpeed = (sint8)(enc.pctRight / 10);
                }
            }

            XCORE_statusPublish(&status);

            /* map -100..+100 (protocol) to -1000..+1000 (motor algorithm) */
            XCORE_motorSetTarget((sint16)speeds.left * 10, (sint16)speeds.right * 10,
                                 ROBOT_isEmergencyStop());
            if (!ROBOT_isEmergencyStop() && ROBOT_getFaultCode() == 0)
            {
                XCORE_estopClear();
            }
        }

        XCORE_logService();

        vTaskDelay(pdMS_TO_TICKS(10));
    }
}
#endif

void core0_main(void)
{
    IfxCpu_enableInterrupts();

    /* CPU0 watchdog ON (doc 21 SS18 C8): fed by the robot control task
     * every 10 ms. A hung scheduler or a starved robot task resets the
     * device in ~0.5 s, and vApplicationStackOverflowHook relies on this
     * to turn a stack overflow into a reset instead of a silent spin.
     * After the reset the boot comes back with all motors stopped. */
    WDG_enableCpu();

    /* Safety watchdog stays disabled on purpose: the SM watchdog is the
     * root of the production chain (doc 21 SS7.2) and must only run with
     * its feed conditions (CPU1 seq advancing && link healthy), which the
     * demo does not have yet. */
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* Shared memory must be initialized before any core leaves the sync event */
    XCORE_init();

    /* Calibration record from DFlash (doc 34 SS8.3), loaded and published
     * while CPU1/CPU2 are still held at the sync event - the motor core then
     * starts on the stored signs and speed parameters instead of the
     * compile-time defaults. A DFlash read is memory-mapped: no stall. */
    STIME_init();
    /* CALIB_init() logs its load outcome over ASCLIN0, so the UART must be
     * up first; a print against the un-initialised driver traps (bus error
     * on the ASCLIN0 SFR at 0xF0030000, whose clock is still gated). */
    UART_init();
    CALIB_init();

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

#if defined(__TASKING__)
    /* UART was brought up before CALIB_init above; say so now that the
     * scheduler-free init phase is done. */
    UART_println("UART initialized");
    UART_println(g_app_version);   /* "APPFW tc275_car vX.Y.Z" (mw/app_version.h) */


    /* Configure LED1 as push-pull output */
    IfxPort_setPinMode(&MODULE_P00, LED1_PIN_INDEX, IfxPort_Mode_outputPushPullGeneral);

    /* Create the LED blinky task */
    xTaskCreate(vBlinkyTask, "blinky", configMINIMAL_STACK_SIZE, NULL, 1, NULL);

    /* Create the loopback echo test task */
    xTaskCreate(vUartEchoTask, "echo", configMINIMAL_STACK_SIZE, NULL, 1, NULL);

    /* Initialize the robot state machine / motion controller */
    ROBOT_init();

    /* Create the robot control task (10 ms safety + status upload) */
    xTaskCreate(vRobotControlTask, "robot", configMINIMAL_STACK_SIZE * 2, NULL, 2, NULL);

    /* Start the FreeRTOS scheduler */
    vTaskStartScheduler();
#endif

    while(1)
    {
    }
}

#if defined(__TASKING__)
/* FreeRTOS detected a task running past its stack (method 1, checked at
 * context switch). Report on the console, then stop feeding: the CPU0
 * watchdog enabled in core0_main bites in ~0.5 s and the reset lands the
 * system in the safe (motors stopped) boot state. Spinning here without
 * the watchdog armed - the old behavior - swallowed the fault. */
void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName)
{
    (void)xTask;

    /* Print with the TX ISR still enabled (the blocking write waits on it
     * to drain the software FIFO), then take interrupts away so the pump
     * below is the only writer, then spin. */
    UART_println("FATAL: stack overflow in task:");
    UART_println(pcTaskName);

    __disable();                     /* freeze the fault scene           */
    UART_flushPolling();             /* push what is left out, no ISR    */

    while (1)
    {
        __nop();                     /* un-fed watchdog resets in ~0.5 s */
    }
}
#endif
