/**********************************************************************************************************************
 * \file Cpu2_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
/* CPU2 - bare-metal core: the board link to the ESP32-C6.
 * Two builds share this file:
 *   default      : demo path, AT firmware on ASCLIN1 (P15.0/P15.1) + the AA 55
 *                  byte protocol. Kept until gate G1 passes on the bench.
 *   USE_SPI_LINK : production path, SF frames over QSPI3 half duplex
 *                  transactions (doc/20-design/22-link-spi-design.md).
 * ASCLIN1 and its interrupts belong to this core; no FreeRTOS API may be used
 * here - the kernel runs on CPU0. */
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "stime.h"
#include "protocol.h"

#ifdef USE_SPI_LINK
#include "com/link.h"
#include "xcore.h"
#include <string.h>

/* 22 SS6: telemetry is aggregated at 20 ms. */
#define LINK_TELEMETRY_PERIOD_MS  20u

/* SDD SS10: fwVer is 0x00MMmmpp. This is the SDD V1.2 baseline build; the
 * buildhash half of the §10 version string has no slot in a u32 and is not
 * carried. */
#define LINK_FW_VERSION           0x00010200u

/* Telemetry fields with a measured source in this build are filled, the rest are
 * zero. The zeros are not placeholders: each one names what has to exist first.
 * Filling a field with a number from another unit would be worse than a zero,
 * because the C6 forwards these bytes to the phone, which prints mm/s, mV and mm.
 *   vTargetL/R, vMeasL/R - mm/s. The speed figures this build has are the demo's
 *                  +-100 percent in ProtocolStatus and CPU1's target in
 *                  0.1 percent units; the mm/s domain needs the encoder channel
 *                  of SDD SS5.4 (doc 23 SS6 also lacks the wheel circumference
 *                  that would make the conversion definable).
 *   batteryMv/Pct- no ADC channel is wired up in this build.
 *   odo*         - same reason as vMeas: needs the encoder counts.
 *   linkRttMs    - needs the HBT transaction the RTT measurement rides on.
 *   hwRev        - no board id source yet; the DPT flow of SDD SS10 reads it
 *                  before it reads anything else, so it is the first field to
 *                  fill once the hardware revision has a home.
 * linkErrRate is computed from the link's own counters below. */
static void link_sendTelemetry(void)
{
    Link_Health    health;
    ProtocolStatus status;
    SF_Telemetry   tel;
    uint32         total;
    uint32         err;
    uint32         rate;
    uint32         perTenth;

    XCORE_statusGet(&status);

    memset(&tel, 0, sizeof(tel));
    tel.uptimeMs  = STIME_nowMs();
    tel.state     = status.state;
    tel.faultCode = status.faultCode;   /* demo code set is 8 bit, widened as-is */
    tel.fwVer     = LINK_FW_VERSION;

    /* SDD SS6.1c / 22 SS5.5: linkErrRate keeps its meaning but changes source -
     * frames this core's codec rejected, over frames it saw, in units of 0.1%
     * (c6_proto/proto_frames.h declares that unit, so a plain percentage would
     * understate the link by a factor of ten). A frame that failed the CRC is in
     * the denominator only. The scaling divides first because err * 1000 overflows
     * uint32 on a noisy long-running link; 255 saturates at 25.5%, which already
     * means "the link is down" and is reported as ERR_LINK_LOST separately. */
    LINK_getHealth(&health);
    err   = health.stats.crcErrors + health.stats.seqErrors;
    total = health.stats.rxFrames + err;
    rate  = 0u;
    if ((err > 0u) && (total > 0u))
    {
        if (total < 1000u)
        {
            rate = (err * 1000u) / total;   /* provably within range */
        }
        else
        {
            perTenth = total / 1000u;   /* frames per 0.1%, >= 1 here */
            rate = err / perTenth;
        }
        if (rate > 255u)
        {
            rate = 255u;
        }
    }
    tel.linkErrRate = (uint8)rate;

    /* seq is stamped by the link, which owns the order frames actually go out in. */
    (void)LINK_sendTelemetry(&tel);
}
#else
#include "wifi_at.h"
#endif

extern IfxCpu_syncEvent cpuSyncEvent;

void core2_main(void)
{
#ifdef USE_SPI_LINK
    uint32 nextTelMs;
#endif

    IfxCpu_enableInterrupts();

    /* !!WATCHDOG2 IS DISABLED HERE!!
     * Enable the watchdog and service it periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    STIME_init();

#ifdef USE_SPI_LINK

    /* First rung of the clock ladder: gate G1 is a waveform compatibility test,
     * so it starts at 1 MHz and only climbs on measured error rates (22 SS8). */
    LINK_init(SPIHAL_CLK_1M);
    nextTelMs = STIME_nowMs() + LINK_TELEMETRY_PERIOD_MS;

    while (1)
    {
        LINK_main();                       /* pump: registers, read, write      */

        if ((sint32)(STIME_nowMs() - nextTelMs) >= 0)
        {
            nextTelMs += LINK_TELEMETRY_PERIOD_MS;
            link_sendTelemetry();          /* keeps WRDMA traffic flowing for G5 */
        }
    }

#else

    /* Initialize the binary protocol parser (byte stream comes from WiFi) */
    PROTO_init();

    /* Initialize the ESP32-C6 AT module on ASCLIN1 (P15.0 TX / P15.1 RX) */
    WIFI_init();

    WIFI_main();                           /* never returns */

    while (1)
    {
    }

#endif
}
