/**********************************************************************************************************************
 * \file Cpu2_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
/* CPU2 - bare-metal core: the board link to the ESP32-C6.
 * Two builds share this file:
 *   default      : demo path, AT firmware on ASCLIN1 (P15.0/P15.1) + the AA 55
 *                  byte protocol. Kept until gate G1 passes on the bench.
 *   USE_SPI_LINK : production path, SF frames over QSPI3 half duplex
 *                  transactions (doc/20-design/22-link-spi-design.md).
 * ASCLIN1 and its interrupts belong to this core; no FreeRTOS API may be used
 * here - the kernel runs on CPU0. */
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "stime.h"
#include "protocol.h"

#ifdef USE_SPI_LINK
#include "com/link.h"
#include "xcore.h"

/* 22 SS6: telemetry is aggregated at 20 ms. */
#define LINK_TELEMETRY_PERIOD_MS  20u

static void link_sendTelemetry(void)
{
    ProtocolStatus status;
    uint8          tel[6];

    XCORE_statusGet(&status);

    /* Same six fields in the same order as the demo's 0x40 status reply, so the
     * C6 bridge maps this 1:1 onto the phone facing v2 frame (22 SS5.5). Built
     * byte by byte instead of casting the struct: wire order must not depend on
     * a compiler's padding decisions. */
    tel[0] = status.state;
    tel[1] = (uint8)status.leftSpeed;
    tel[2] = (uint8)status.rightSpeed;
    tel[3] = status.heartbeatOk;
    tel[4] = status.faultCode;
    tel[5] = status.emergencyStop;

    /* A refused send is counted in Link_Health.stats.txQueueFull, not lost. */
    (void)LINK_send(SF_TYPE_TEL, SF_CID_TELEMETRY, tel, (uint8)sizeof(tel));
}
#else
#include "wifi_at.h"
#endif

extern IfxCpu_syncEvent cpuSyncEvent;

void core2_main(void)
{
#ifdef USE_SPI_LINK
    uint32 nextTelMs;
#endif

    IfxCpu_enableInterrupts();

    /* !!WATCHDOG2 IS DISABLED HERE!!
     * Enable the watchdog and service it periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    STIME_init();

#ifdef USE_SPI_LINK

    /* First rung of the clock ladder: gate G1 is a waveform compatibility test,
     * so it starts at 1 MHz and only climbs on measured error rates (22 SS8). */
    LINK_init(SPIHAL_CLK_1M);
    nextTelMs = STIME_nowMs() + LINK_TELEMETRY_PERIOD_MS;

    while (1)
    {
        LINK_main();                       /* pump: registers, read, write      */

        if ((sint32)(STIME_nowMs() - nextTelMs) >= 0)
        {
            nextTelMs += LINK_TELEMETRY_PERIOD_MS;
            link_sendTelemetry();          /* keeps WRDMA traffic flowing for G5 */
        }
    }

#else

    /* Initialize the binary protocol parser (byte stream comes from WiFi) */
    PROTO_init();

    /* Initialize the ESP32-C6 AT module on ASCLIN1 (P15.0 TX / P15.1 RX) */
    WIFI_init();

    WIFI_main();                           /* never returns */

    while (1)
    {
    }

#endif
}
