#!/usr/bin/env python3
"""Generate test/host/test_vectors.h for the TCFW bundle host tests.

Builds a deterministic signed "TCFW" bundle exactly the way the C6 signing
tool (esp32c6_car tools/sign_bundle.py) builds "C6FW" bundles: header fields LE,
ed25519 signature over the FIRST 84 bytes, payload digest = SHA-512[:32].
The app image is LCG-generated so the bytes are reproducible without
shipping a binary blob, and its length is deliberately not page-aligned
(65749 B) to exercise the receiver's partial-page staging.

Also emits a bundle signed with a different key (verification must fail).

Usage: python tools/gen_test_vectors.py   (run from the repo root)
"""
import hashlib
import os
import struct
import sys
import zlib

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(REPO, os.pardir, "esp32c6_car", "tools"))
import ed25519_ref as ed  # noqa: E402

HDR_LEN = 148
SIGNED_LEN = 84
SEED = bytes.fromhex(open(os.path.join(REPO, os.pardir, "esp32c6_car", "tools",
                                       "keys", "ed25519_dev.seed")).read().strip())
OTHER_SEED = bytes(range(32))          # never a real key, just a different one


def lcg_stream(n, seed=0x5A17C0DE):
    """Deterministic pseudo-random image bytes (WC-RNG quality irrelevant)."""
    out = bytearray(n)
    x = seed
    for i in range(n):
        x = (1103515245 * x + 12345) & 0xFFFFFFFF
        out[i] = (x >> 16) & 0xFF
    return bytes(out)


def build_bundle(app, seed, flags=1):
    total = HDR_LEN + len(app)
    head = bytearray()
    head += b"TCFW"
    head += struct.pack("<BBH", 1, flags, HDR_LEN)
    head += struct.pack("<I", total)
    head += struct.pack("<I", len(app))
    head += hashlib.sha512(app).digest()[:32]
    head += struct.pack("<I", 0)          # rsv_len
    head += bytes(32)                     # rsv_sha
    assert len(head) == SIGNED_LEN
    sig = ed.sign(seed, bytes(head))
    return bytes(head) + sig + app


def c_bytes(data, name, per_line=12):
    rows = []
    for i in range(0, len(data), per_line):
        rows.append("    " + ", ".join("0x%02x" % b for b in data[i:i + per_line]))
    return "static const unsigned char %s[%d] =\n{\n%s\n};\n" % (
        name, len(data), ",\n".join(rows))


def main():
    app = lcg_stream(65749)
    bundle = build_bundle(app, SEED)
    wrong = build_bundle(app, OTHER_SEED)
    pub = ed.secret_to_public(SEED)

    assert len(bundle) == 148 + len(app)
    assert zlib.crc32(bundle) != 0

    hdr = """/*
 * test_vectors.h - generated by tools/gen_test_vectors.py, do not edit.
 *
 * tv_bundle  : valid TCFW bundle (dev key), app image = 65749 LCG bytes
 * tv_wrongkey: same image signed with a different key - must fail verify
 * Expected CRC-32 values are zlib.crc32 (IEEE), matching mw/ota/crc32.c.
 */
#ifndef TEST_VECTORS_H
#define TEST_VECTORS_H

#define TV_APP_LEN        %du
#define TV_BUNDLE_LEN     %du
#define TV_APP_CRC32      0x%08xu
#define TV_BUNDLE_CRC32   0x%08xu

""" % (len(app), len(bundle), zlib.crc32(app), zlib.crc32(bundle))

    hdr += c_bytes(pub, "tv_pub")
    hdr += "\n" + c_bytes(bundle, "tv_bundle")
    hdr += "\n" + c_bytes(wrong, "tv_wrongkey")
    hdr += "\n#endif /* TEST_VECTORS_H */\n"

    out = os.path.join(REPO, "test", "host", "test_vectors.h")
    open(out, "w", newline="\n").write(hdr)
    print("wrote %s (%d bytes): bundle %d B, app %d B, pub %s..." %
          (out, len(hdr), len(bundle), len(app), pub.hex()[:16]))


if __name__ == "__main__":
    main()
