/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
/* CPU0 - FreeRTOS core: robot control task (safety checks + command
 * execution + status publishing), the VL53L5CX ToF service task (I2C0 owner),
 * console UART, LED. The motor algorithm runs on CPU1 and the ESP32-C6 WiFi
 * link on CPU2 (see Cpu1/Cpu2_Main.c). */
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "IfxPort.h"
#include "bsp/stime.h"
#include "bsp/tof.h"
#include "bsp/uart.h"
#include "bsp/wdg.h"
#include "mw/calib/calib_store.h"
#include "mw/diag/diag_service.h"
#include "mw/xcore/xcore.h"
#include "mw/proto/protocol.h"
#include "mw/app_version.h"
#include "mw/sf/sf_frame.h"
#include "app/robot.h"
#include "app/fusion.h"
#include <string.h>

static Fusion g_driveFusion;
static FusionInput g_fusionInput;


#include "FreeRTOS.h"
#include "task.h"


IfxCpu_syncEvent cpuSyncEvent = 0;

#define LED1_PIN_INDEX 5  /* LED1 on KIT_AURIX_TC275_LITE, Port 0 Pin 5 */
#define BLINKY_PERIOD  250U


static void vBlinkyTask(void *pvParameters)
{
    while (1)
    {
        IfxPort_setPinState(&MODULE_P00, LED1_PIN_INDEX, IfxPort_State_toggled);
        vTaskDelay(pdMS_TO_TICKS(BLINKY_PERIOD));
    }
}

/* Loopback echo test: any byte received on ASCLIN0 RX is echoed back on TX.
 * Type a character in the terminal; if it comes back, the whole USB-UART
 * path (P14.1 <-> FT2232 <-> COM port) works. */
static void vUartEchoTask(void *pvParameters)
{
    while (1)
    {
        UART_echoTask();
    }
}

/* VL53L5CX ToF service task (doc 30-tc275/36-tof-driver.md): owns I2C0
 * (SCL=P02.5 / SDA=P02.4) and the sensor's bring-up ladder, then reads frames.
 *
 * It runs one priority BELOW the robot task deliberately. Bringing the sensor
 * up costs a ~3 s, 84 KB firmware download over the bus, and the robot task is
 * what feeds the CPU0 watchdog every 10 ms; at priority 2 it preempts this task
 * whenever it is ready, so no transaction here can delay that feed.
 *
 * TOF_init() is called inside the task, not from core0_main: the driver's
 * transaction timeouts are tick-based, and the tick does not advance before
 * vTaskStartScheduler() runs. */
static void vTofTask(void *pvParameters)
{
    (void)pvParameters;

    TOF_init();

    while (1)
    {
        TOF_task();
        vTaskDelay(pdMS_TO_TICKS(TOF_TASK_PERIOD_MS));
    }
}

/* Robot control task (10 ms): drain the command queue filled by CPU2 (WiFi),
 * run the safety state machine, publish the robot status for CPU2's replies
 * and forward the side speed targets to the CPU1 motor algorithm. Also
 * drains the cross-core log ring to the console UART. */
static void vRobotControlTask(void *pvParameters)
{
    (void)pvParameters;

    while (1)
    {
        WDG_serviceCpu();     /* CPU0 WDT feed point, 10 ms (vTaskDelay below) */

        XcoreCmdMsg msg;

        while (XCORE_cmdPop(&msg))
        {
            PROTO_handleCommand(msg.cmd, msg.data, msg.len);
        }

        ROBOT_task();
        DIAG_tick();

        /* DPT result mailbox + deferred calibration saves (doc 34 SS8.3).
         * A save masks this core's interrupts for tens of ms; the 10 ms feed
         * above and the one below bound the gap well inside the ~1.4 s CPU
         * watchdog window. */
        CALIB_tick();
        WDG_serviceCpu();

        /* Version beacons to C6->S3 (SF EVT 0x24/0x25, surfacing as a
         * {"t":"tcver"} JSON on the C6): pushed at task start, re-sent
         * every 5 s so a freshly connected remote always catches one, and
         * sent at once on a DIAG 0x53/0x24 request (S3 SYSTEM page tap). */
        {
            static uint32 s_lastBeaconMs = 0u;
            static uint8  s_beaconInit   = 0u;
            uint32        nowMs = (uint32)xTaskGetTickCount() * portTICK_PERIOD_MS;
            uint8         asked = app_ver_take_request();

            if ((!s_beaconInit) || (asked != 0u) || ((nowMs - s_lastBeaconMs) >= 5000u))
            {
                XcoreEvtFrame frame;
                uint8         appBuf[APP_VER_EVT_LEN];
                uint8         sblBuf[APP_VER_EVT_LEN];
                uint8         i;

                app_ver_evt_build(appBuf, sblBuf);

                frame.type = SF_TYPE_EVT;
                frame.len  = APP_VER_EVT_LEN;
                frame.cid  = SF_CID_EVT_APP_VER;
                for (i = 0u; i < APP_VER_EVT_LEN; i++)
                {
                    frame.payload[i] = appBuf[i];
                }
                (void)XCORE_evtPush(&frame);

                frame.cid = SF_CID_EVT_SBL_VER;
                for (i = 0u; i < APP_VER_EVT_LEN; i++)
                {
                    frame.payload[i] = sblBuf[i];
                }
                (void)XCORE_evtPush(&frame);

                s_lastBeaconMs = nowMs;
                s_beaconInit   = 1u;
            }
        }

        {
            ProtocolStatus status;
            RobotSpeeds    speeds = ROBOT_getSpeeds();

            {
                XcoreEncoder enc;
                XcoreImu imu;
                XcoreRecordLive live;
                uint8 i;
                XCORE_encoderRead(&enc); XCORE_imuRead(&imu);
                XCORE_recordGet(&live); XCORE_tofRead(&g_fusionInput.tof);
                g_fusionInput.nowMs = (uint32)xTaskGetTickCount() * portTICK_PERIOD_MS;
                g_fusionInput.imuSeq = imu.seq; g_fusionInput.imuAlive = imu.alive;
                g_fusionInput.encoderSeq = enc.seq;
                g_fusionInput.encEdgeAgeMs[0] = enc.edgeAgeMs[0];
                g_fusionInput.encEdgeAgeMs[1] = enc.edgeAgeMs[1];
                g_fusionInput.wheelsCalibrated = live.rec.src != CALIB_SRC_DEFAULT;
                g_fusionInput.fullScaleMmS = live.rec.fullScaleMmS;
                g_fusionInput.wheelMmS[0] = enc.vMeasLeftMmS;
                g_fusionInput.wheelMmS[1] = enc.vMeasRightMmS;
                g_fusionInput.request[0] = (sint16)speeds.left * 10;
                g_fusionInput.request[1] = (sint16)speeds.right * 10;
                for (i=0u; i<3u; i++) {
                    g_fusionInput.accMg[i] = imu.accMilliG[i];
                    g_fusionInput.gyroMdps[i] = imu.gyroMilliDps[i];
                }
                for (i=0u; i<4u; i++) g_fusionInput.counts[i] = enc.raw[i];
                FUSION_step(&g_driveFusion, &g_fusionInput);
                XCORE_fusionPublish(&g_driveFusion.out);
                {
                    static XcoreLogGate gate;
                    static const char *const action[] = {"none", "limit_speed", "stop_obstacle",
                        "stop_tof_unavailable", "stop_tilt", "stop_encoder_unavailable"};
                    static const char *const tofMode[] = {"blind", "tracked",
                        "degraded", "open_clear"};
                    FusionOutput *out = &g_driveFusion.out;
                    /* Fold tofMode into the signature: OPEN_CLEAR and DEGRADED
                     * share the LIMITED wire bit, so a scene reclassification
                     * that changes the cap must still re-log. */
                    uint32 signature = ((uint32)out->flags & 0xEFu) | ((uint32)out->reason << 8u)
                        | ((uint32)g_driveFusion.tofMode << 16u);
                    boolean urgent = (out->reason >= FUSION_OBSTACLE) ? TRUE : FALSE;
                    if (XCORE_logDue(&gate, g_fusionInput.nowMs, signature, 5000u, 1000u, urgent)) {
                        const char *permission = "allowed";
                        if (!g_fusionInput.wheelsCalibrated) permission = "blocked_wheel_calibration";
                        else if (!(out->flags & FUSION_ENCODER_OK)) permission = "blocked_encoder";
                        else if (!(out->flags & (FUSION_TOF_OK | FUSION_TOF_LIMITED))) permission = "blocked_tof";
                        else if (out->nearestMm && out->nearestMm <= g_driveFusion.cfg.marginMm) permission = "blocked_near_obstacle";
                        else if (out->flags & FUSION_NEUTRAL_REQUIRED) permission = "blocked_release_required";
                        else if (g_driveFusion.tofMode == FUSION_MODE_OPEN) permission = "open_space";
                        else if (out->flags & FUSION_TOF_LIMITED) permission = "limited_tof_coverage";
                        if (out->reason == FUSION_TILT) permission = "blocked_tilt";
                        XCORE_LOG_FIELDS("[FUSION]",
                            XL_U("uptime_ms", g_fusionInput.nowMs),
                            XL_S("action", out->reason < 6u ? action[out->reason] : "unknown"),
                            XL_S("forward", permission), XL_S("tof_mode",
                                g_driveFusion.tofMode < 4u ? tofMode[g_driveFusion.tofMode] : "unknown"),
                            XL_U("nearest_mm", out->nearestMm),
                            XL_U("forward_cap_mm_s", out->capMmS), XL_I("speed_mm_s", out->speedMmS),
                            XL_U("tof_age_ms", out->tofAgeMs), XL_U("trusted_zones", out->validZones),
                            XL_U("no_target_zones", g_driveFusion.tofNoTarget),
                            XL_U("unknown_zones", g_driveFusion.tofUnknown),
                            XL_U("open_clear_frames", g_driveFusion.openClearFrames),
                            /* Compile-time FUSION_CFG_PROTECTION: 0 = the cap and
                             * permission below are advisory only, nothing is
                             * enforced (bench/diagnosis build, doc 37). */
                            XL_U("protection", FUSION_CFG_PROTECTION));
                        XCORE_LOG_FIELDS("[FUSION_CONTROL]", XL_U("uptime_ms", g_fusionInput.nowMs),
                            XL_I("target_left_pct_x10", out->effective[0]),
                            XL_I("target_right_pct_x10", out->effective[1]),
                            XL_U("brake", out->brake), XL_H("health_flags", out->flags));
                        XCORE_LOG_FIELDS("[FUSION_HEALTH]",
                            XL_U("uptime_ms", g_fusionInput.nowMs),
                            XL_U("tof_valid", out->flags & FUSION_TOF_OK ? 1u : 0u),
                            XL_U("imu_fresh", out->flags & FUSION_IMU_OK ? 1u : 0u),
                            XL_U("encoder_fresh", out->flags & FUSION_ENCODER_OK ? 1u : 0u),
                            XL_S("imu_axes", out->flags & FUSION_CALIBRATED ? "calibrated" : "uncalibrated"),
                            XL_S("gyro_bias", out->flags & FUSION_BIAS_READY ? "ready" : "learning"),
                            XL_U("wheel_gyro_mismatch", out->flags & FUSION_SLIP ? 1u : 0u),
                            XL_U("release_required", out->flags & FUSION_NEUTRAL_REQUIRED ? 1u : 0u),
                            XL_U("log_dropped_total", XCORE_logDropped()));
                    }
                }
            }

            status.state         = ROBOT_getState();
            status.leftSpeed     = (sint8)(g_driveFusion.out.effective[0] / 10);
            status.rightSpeed    = (sint8)(g_driveFusion.out.effective[1] / 10);
            status.heartbeatOk   = ROBOT_isHeartbeatOk() ? 1 : 0;
            status.faultCode     = ROBOT_getFaultCode();
            status.emergencyStop = ROBOT_isEmergencyStop() ? 1 : 0;

            /* Measured wheel speed replaces the commanded echo once the Hall
             * encoders report activity; until then the old behavior holds. */
            {
                XcoreEncoder enc;

                XCORE_encoderRead(&enc);
                if (enc.alive)
                {
                    status.leftSpeed  = (sint8)(enc.pctLeft / 10);
                    status.rightSpeed = (sint8)(enc.pctRight / 10);
                }
            }

            XCORE_statusPublish(&status);

            /* map -100..+100 (protocol) to -1000..+1000 (motor algorithm) */
            XCORE_motorSetTarget(g_driveFusion.out.effective[0], g_driveFusion.out.effective[1],
                                 ROBOT_isEmergencyStop() || g_driveFusion.out.brake);
            if (!ROBOT_isEmergencyStop() && ROBOT_getFaultCode() == 0)
            {
                XCORE_estopClear();
            }
        }

        XCORE_logService();

        vTaskDelay(pdMS_TO_TICKS(10));
    }
}


void core0_main(void)
{
    IfxCpu_enableInterrupts();

    /* CPU0 watchdog ON (doc 21 SS18 C8): fed by the robot control task
     * every 10 ms. A hung scheduler or a starved robot task resets the
     * device in ~1.4 s (expiry raises an NMI whose hook in
     * Configurations/Ifx_Cfg.h triggers a software reset - the hardware
     * alone would only raise NMI and wedge), and
     * vApplicationStackOverflowHook relies on this
     * to turn a stack overflow into a reset instead of a silent spin.
     * After the reset the boot comes back with all motors stopped. */
    WDG_enableCpu();

    /* Safety watchdog stays disabled on purpose: the SM watchdog is the
     * root of the production chain (doc 21 SS7.2) and must only run with
     * its feed conditions (CPU1 seq advancing && link healthy), which the
     * demo does not have yet. */
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    /* Shared memory must be initialized before any core leaves the sync event */
    XCORE_init();

    /* Calibration record from DFlash (doc 34 SS8.3), loaded and published
     * while CPU1/CPU2 are still held at the sync event - the motor core then
     * starts on the stored signs and speed parameters instead of the
     * compile-time defaults. A DFlash read is memory-mapped: no stall. */
    STIME_init();
    /* CALIB_init() logs its load outcome over ASCLIN0, so the UART must be
     * up first; a print against the un-initialised driver traps (bus error
     * on the ASCLIN0 SFR at 0xF0030000, whose clock is still gated). */
    UART_init();
    CALIB_init();

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);


    /* UART was brought up before CALIB_init above; say so now that the
     * scheduler-free init phase is done. */
    UART_println("UART initialized");
    UART_println(g_app_version);   /* "APPFW tc275_car vX.Y.Z" (mw/app_version.h) */
    if (sbl_version_string())
        UART_println(sbl_version_string());   /* "SBLFW tc275_sbl vX.Y.Z" @0x80007E00 */


    /* Configure LED1 as push-pull output */
    IfxPort_setPinMode(&MODULE_P00, LED1_PIN_INDEX, IfxPort_Mode_outputPushPullGeneral);

    /* Create the LED blinky task */
    xTaskCreate(vBlinkyTask, "blinky", configMINIMAL_STACK_SIZE, NULL, 1, NULL);

    /* Create the loopback echo test task */
    xTaskCreate(vUartEchoTask, "echo", configMINIMAL_STACK_SIZE, NULL, 1, NULL);

    /* Create the ToF task (I2C0 owner). Priority 1, under the robot task: see
     * vTofTask. Stack is four times minimal because the vendor driver's deepest
     * function holds two 64-element grids (uint32_t signal_grid + int16_t
     * range_grid, 384 bytes of locals, vl53l5cx_api.c:97-98) and its call chain
     * runs several frames deep. */
    xTaskCreate(vTofTask, "tof", configMINIMAL_STACK_SIZE * 4, NULL, 1, NULL);

    /* Initialize the robot state machine / motion controller */
    ROBOT_init();
    DIAG_init();
    FUSION_init(&g_driveFusion);

    /* Create the robot control task (10 ms safety + status upload) */
    xTaskCreate(vRobotControlTask, "robot", configMINIMAL_STACK_SIZE * 2, NULL, 2, NULL);

    /* Start the FreeRTOS scheduler */
    vTaskStartScheduler();

    while(1)
    {
    }
}


/* FreeRTOS detected a task running past its stack (method 1, checked at
 * context switch). Report on the console, then stop feeding: the CPU0
 * watchdog enabled in core0_main expires in ~1.4 s, its NMI (hook in
 * Configurations/Ifx_Cfg.h) triggers the software reset, and the reset
 * lands the system in the safe (motors stopped) boot state. Spinning here
 * without the watchdog armed - the old behavior - swallowed the fault. */
void vApplicationStackOverflowHook(TaskHandle_t xTask, char *pcTaskName)
{
    (void)xTask;

    /* Print with the TX ISR still enabled (the blocking write waits on it
     * to drain the software FIFO), then take interrupts away so the pump
     * below is the only writer, then spin. */
    UART_println("FATAL: stack overflow in task:");
    UART_println(pcTaskName);

    __disable();                     /* freeze the fault scene           */
    UART_flushPolling();             /* push what is left out, no ISR    */

    while (1)
    {
        __nop();                     /* un-fed watchdog expires in ~1.4 s, NMI hook resets */
    }
}
