/**********************************************************************************************************************
 * \file Cpu1_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
/* CPU1 - bare-metal core: motor algorithm. Owns the GTM/TB6612 motor BSP,
 * the Hall encoders, the battery ADC and the LSM6DSV16BX IMU (QSPI1), and
 * runs a 1 kHz superloop (slew-rate ramps, e-stop brake, command-loss
 * watchdog). No FreeRTOS API may be used here - the kernel runs on CPU0. */
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "bsp/motor.h"
#include "bsp/wdg.h"
#include "rt/motor_algo.h"
#include "rt/encoder.h"
#include "bsp/stime.h"

extern IfxCpu_syncEvent cpuSyncEvent;

void core1_main(void)
{
    IfxCpu_enableInterrupts();

    /* CPU1 (motor core) watchdog ON, fed from the 1 kHz loop inside
     * MOTOR_ALGO_run() (doc 21 SS7.2/SS18 C8). If the loop sticks, the
     * watchdog expires in ~1.4 s and its NMI (hook in
     * Configurations/Ifx_Cfg.h) software-resets the whole device; the boot
     * path back leaves every TB6612 channel stopped (MOTOR_init duty 0 +
     * MOTOR_stopAll) with zero targets, i.e. the safe state. */
    WDG_enableCpu();

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    STIME_init();

    /* Initialize the TB6612 motor drivers (4 channels, 2x TB6612) */
    MOTOR_init();

    /* Wheel Hall encoder decode (GTM TIM0, needs the CMU CLK0 that
     * MOTOR_init set up). ENCODER_task() runs inside the 1 kHz loop. */
    ENCODER_init();

    MOTOR_ALGO_init();
    MOTOR_ALGO_run();                        /* never returns */

    while(1)
    {
    }
}
