/**********************************************************************************************************************
 * \file Cpu2_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
/* CPU2 - bare-metal core: the board link to the ESP32-C6.
 * SF frames over QSPI3 half duplex transactions, doc/20-design/22-link-spi-design.md.
 * QSPI3 and its pin muxing belong to this core; no FreeRTOS API may be used
 * here - the kernel runs on CPU0. */
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "bsp/stime.h"
#include "mw/proto/protocol.h"

#include "com/link.h"
#include "com/ota_app.h"
#include "mw/xcore/xcore.h"
#include "bsp/adc.h"
#include <string.h>

/* 22 SS6: telemetry is aggregated at 20 ms. */
#define LINK_TELEMETRY_PERIOD_MS  20u

/* Bench diagnostic line rate. Slow on purpose: it is for a human watching the
 * serial console, not for the control path, and one line per 500 ms keeps the
 * shared log ring and ASCLIN0 well clear of the 20 ms telemetry traffic. */
#define LINK_DIAG_PERIOD_MS       500u

/* SDD SS10: fwVer is 0x00MMmmpp. Derived from mw/app_version.h so the
 * telemetry slot always matches the firmware version string (the buildhash
 * half of the §10 version string has no slot in a u32 and is not carried). */
#include "mw/app_version.h"
#define LINK_FW_VERSION           ((((uint32)APP_VERSION_MAJOR) << 16) |                                    (((uint32)APP_VERSION_MINOR) << 8) |                                    ((uint32)APP_VERSION_PATCH))

/* Telemetry fields with a measured source in this build are filled, the rest are
 * zero. The zeros are not placeholders: each one names what has to exist first.
 * Filling a field with a number from another unit would be worse than a zero,
 * because the C6 forwards these bytes to the phone, which prints mm/s, mV and mm.
 *   vMeasL/R     - mm/s, straight from CPU1's encoder task through the xcore
 *                  encoder block (doc 21 SS6.3: the SS5.1 encoder channel this
 *                  field was waiting for). A dead or stopped encoder reads 0,
 *                  which is honest in both cases - the payload has no alive bit.
 *   odoSessionMm - overflow-free average of the two side odometries; both are
 *                  absolute accumulators, so the average is the distance the
 *                  chassis covered, straight or curved.
 *   vTargetL/R   - the CPU0 command (percent*10) converted to mm/s through
 *                  the calibration record's fullScaleMmS (doc 34 SS8.2), the
 *                  same number CPU1 divides the measured speed by, so both
 *                  columns share one calibration and follow a REC_SET at once
 *                  (SDD SS5.2 servo landed 2026-09-27; before that the
 *                  target was a raw percent and stayed 0 here).
 *   batteryMv/Pct- VIN from CPU1's VADC (D24A J6-1 divider on AN4/X2-23,
 *                  EMA-filtered, through the xcore battery block). Pct is
 *                  derived with ADC_BATT_CELLS, an assumption until the cell
 *                  count question (SDD SS16 Q1) gets a config home; mV is
 *                  the measurement, pct is the display nicety.
 *   odoTotalMm   - needs DFlash persistence (doc 21 SS4.3) on top of the encoder.
 *   linkRttMs    - needs the HBT transaction the RTT measurement rides on.
 *   hwRev        - no board id source yet; the DPT flow of SDD SS10 reads it
 *                  before it reads anything else, so it is the first field to
 *                  fill once the hardware revision has a home.
 * linkErrRate is computed from the link's own counters below. */

/* Overflow-free average of the two side odometries (both absolute
 * accumulators): the distance the chassis covered, straight or curved. */
static uint32 link_sessionOdoMm(const XcoreEncoder *enc)
{
    return (enc->odoLeftMm / 2u) + (enc->odoRightMm / 2u)
         + ((enc->odoLeftMm & 1u) & (enc->odoRightMm & 1u));
}

/* CPU0's target is percent*10 of full scale; the telemetry field is mm/s.
 * The conversion is the calibration record's full-scale value (doc 34 SS8.2:
 * the same number CPU1 divides the measured speed by, so both columns stay
 * one consistent pair even after a REC_SET changed it). */
static sint16 link_targetToMmS(sint16 pct10)
{
    XcoreRecordLive live;
    sint32          mmS;

    XCORE_recordGet(&live);
    mmS = ((sint32)pct10 * (sint32)live.rec.fullScaleMmS) / 1000;

    if (mmS > 32767)
    {
        mmS = 32767;
    }
    if (mmS < -32768)
    {
        mmS = -32768;
    }
    return (sint16)mmS;
}

/* Event outbox drain (doc 34 SS3.4 / SS9.4): CPU0 pushes the DPT frames,
 * this core owns the TX path. peek + pop-around-send means a full TX queue
 * retries the SAME frame on the next tick instead of dropping it, so one
 * calibration produces exactly one frame. */
static void link_sendPendingEvents(void)
{
    XcoreEvtFrame frame;
    uint8         sent = 0u;

    while ((sent < XCORE_EVT_QUEUE_LEN) && (XCORE_evtPeek(&frame) != FALSE))
    {
        if (LINK_send(frame.type, frame.cid, frame.payload, frame.len) == FALSE)
        {
            break;                  /* backpressure: keep it pending          */
        }
        XCORE_evtPop();
        sent++;
    }
}

static void link_sendTelemetry(void)
{
    Link_Health    health;
    ProtocolStatus status;
    SF_Telemetry   tel;
    XcoreEncoder   enc;
    uint32         total;
    uint32         err;
    uint32         rate;
    uint32         perTenth;

    XCORE_statusGet(&status);
    XCORE_encoderRead(&enc);

    memset(&tel, 0, sizeof(tel));
    tel.uptimeMs  = STIME_nowMs();
    tel.state     = status.state;
    tel.faultCode = status.faultCode;   /* demo code set is 8 bit, widened as-is */
    tel.fwVer     = LINK_FW_VERSION;
    tel.vMeasLeft  = enc.vMeasLeftMmS;
    tel.vMeasRight = enc.vMeasRightMmS;
    tel.odoSessionMm = link_sessionOdoMm(&enc);

    /* Battery: CPU1 measures VIN (D24A J6-1 divider, AN4) at 100 Hz and
     * publishes the filtered mV; pct is the per-cell estimate. */
    tel.batteryMv  = XCORE_battGetMv();
    tel.batteryPct = ADC_battPctFromMv(tel.batteryMv);

    /* The command the drive is currently asked to follow (the CPU0 -> CPU1
     * target, before the servo loop acts on it). CPU0 is the block's only
     * writer, so reading it here is a plain shared-memory peek. */
    {
        sint16  tgtL, tgtR;
        boolean tgtEstop;

        (void)XCORE_motorGetTarget(&tgtL, &tgtR, &tgtEstop);
        tel.vTargetLeft  = link_targetToMmS(tgtL);
        tel.vTargetRight = link_targetToMmS(tgtR);
    }

    /* SDD SS6.1c / 22 SS5.5: linkErrRate keeps its meaning but changes source -
     * frames this core's codec rejected, over frames it saw, in units of 0.1%
     * (c6_proto/proto_frames.h declares that unit, so a plain percentage would
     * understate the link by a factor of ten). A frame that failed the CRC is in
     * the denominator only. The scaling divides first because err * 1000 overflows
     * uint32 on a noisy long-running link; 255 saturates at 25.5%, which already
     * means "the link is down" and is reported as ERR_LINK_LOST separately. */
    LINK_getHealth(&health);
    err   = health.stats.crcErrors + health.stats.seqErrors;
    total = health.stats.rxFrames + err;
    rate  = 0u;
    if ((err > 0u) && (total > 0u))
    {
        if (total < 1000u)
        {
            rate = (err * 1000u) / total;   /* provably within range */
        }
        else
        {
            perTenth = total / 1000u;   /* frames per 0.1%, >= 1 here */
            rate = err / perTenth;
        }
        if (rate > 255u)
        {
            rate = 255u;
        }
    }
    tel.linkErrRate = (uint8)rate;

    /* seq is stamped by the link, which owns the order frames actually go out in. */
    (void)LINK_sendTelemetry(&tel);
}

/* Bench speed line: the figures this core puts into telemetry vMeasL/R and
 * odoSession, on the CPU0 console every 10 seconds so a bench check of the speed
 * display needs no phone on the link. Named fields include units. */
#define LINK_SPEED_PERIOD_MS     10000u

static void link_speedPrint(void)
{
    XcoreEncoder enc;
    sint32       vals[4];

    XCORE_encoderRead(&enc);
    vals[0] = enc.vMeasLeftMmS;
    vals[1] = enc.vMeasRightMmS;
    vals[2] = (sint32)link_sessionOdoMm(&enc);
    vals[3] = enc.alive ? 1 : 0;

    XCORE_LOG_FIELDS("[WHEELS]", XL_U("uptime_ms", STIME_nowMs()),
        XL_I("left_mm_s", vals[0]), XL_I("right_mm_s", vals[1]),
        XL_U("session_odo_mm", vals[2]), XL_U("recent_encoder_edges", vals[3]));
}

extern IfxCpu_syncEvent cpuSyncEvent;

void core2_main(void)
{
    uint32 nextTelMs;
    uint32 nextDiagMs;
    uint32 nextSpdMs;
    uint32 nextFusionMs;

    IfxCpu_enableInterrupts();

    /* CPU2 watchdog intentionally stays DISABLED (doc 21 SS18 C8): a hung
     * link pump cannot move the motors (CPU1's 150 ms command-loss ramp-stop
     * and CPU0's 100 ms heartbeat stop them first), and per doc 21 SS7.2 a
     * CPU2 fault must reset only CPU2 - that needs the production SMU alarm
     * routing. The CPU2 WDT alarm here would reset the whole vehicle.
     * Revisit together with the SS7.2 watchdog chain. */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());

    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&cpuSyncEvent);
    IfxCpu_waitEvent(&cpuSyncEvent, 1);

    STIME_init();

    /* First rung of the clock ladder: gate G1 is a waveform compatibility test,
     * so it starts at 1 MHz and only climbs on measured error rates (22 SS8). */
    LINK_init(SPIHAL_CLK_1M);
    OTAAPP_init();                       /* OTA receiver (doc 24 SS5.3)      */
    nextTelMs  = STIME_nowMs() + LINK_TELEMETRY_PERIOD_MS;
    nextDiagMs = STIME_nowMs() + LINK_DIAG_PERIOD_MS;
    nextSpdMs  = STIME_nowMs() + LINK_SPEED_PERIOD_MS;
    nextFusionMs = STIME_nowMs() + 200u;

    while (1)
    {
        LINK_main();                       /* pump: registers, read, write      */
        OTAAPP_tick();                     /* self-test confirm (doc 24 SS5.2)  */

        if ((sint32)(STIME_nowMs() - nextTelMs) >= 0)
        {
            nextTelMs += LINK_TELEMETRY_PERIOD_MS;
            link_sendTelemetry();          /* keeps WRDMA traffic flowing for G5 */
            link_sendPendingEvents();      /* DPT event frames queued by CPU0    */
        }

        if ((sint32)(STIME_nowMs() - nextFusionMs) >= 0)
        {
            nextFusionMs = STIME_nowMs() + 200u;
            if (LINK_isUp()) {
                static uint32 lastStampMs;
                static uint32 lastChangeMs;
                FusionOutput out;
                uint8 wire[FUSION_WIRE_LEN];
                uint32 nowMs = STIME_nowMs();
                XCORE_fusionRead(&out);
                if (out.stampMs != lastStampMs) {
                    lastStampMs = out.stampMs;
                    lastChangeMs = nowMs;
                }
                /* Network traffic cannot make a frozen CPU0 snapshot fresh. */
                if ((uint32)(nowMs - lastChangeMs) > 250u) {
                    out.flags &= (uint16)~(FUSION_TOF_OK | FUSION_TOF_LIMITED | FUSION_IMU_OK | FUSION_ENCODER_OK);
                    out.reason = FUSION_BLIND;
                    out.capMmS = 0u;
                    out.tofAgeMs = 65535u;
                }
                FUSION_encode(&out, wire);
                (void)LINK_send(SF_TYPE_EVT, FUSION_EVT_CID, wire, FUSION_WIRE_LEN);
            }
        }

        if ((sint32)(STIME_nowMs() - nextDiagMs) >= 0)
        {
            nextDiagMs += LINK_DIAG_PERIOD_MS;
            LINK_diagPrint();              /* bench: dump SPI link state to UART  */
        }

        if ((sint32)(STIME_nowMs() - nextSpdMs) >= 0)
        {
            nextSpdMs += LINK_SPEED_PERIOD_MS;
            link_speedPrint();             /* bench: wheel speeds + odometer     */
        }
    }
}
