/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \brief SBL entry: the secondary bootloader that owns the reset vector (doc 24).
 *
 * Replaces the Blinky template main. The SBL runs on CPU0 only - CPU1/2 stay
 * in reset until the App's own CStart releases them (Configurations/Ifx_Cfg.h
 * sets IFX_CFG_CPU_CSTART_ENABLE_TRICORE1/2 to 0 for this build). Real work
 * lives in sbl/sbl_boot.c: OtaMeta decision ladder, slot jump, safe mode.
 *
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If as long as no such terms of use are
 * agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are solely in the form of
 * machine-executable object code generated by a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"
#include "sbl_led.h"
#include "sbl/sbl_boot.h"
#include "mw/app_version.h"

/* Referenced by the Cpu1/Cpu2 template mains (kept compiled, never started:
 * the App releases the cores, not the SBL). */
IfxCpu_syncEvent g_cpuSyncEvent = 0;

int core0_main(void)
{
    /* The SBL is a no-interrupt, single-core program: leave the interrupt
     * system exactly as CStart left it (globally disabled). */

    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * The SBL boots in well under a watchdog period and hands over to the
     * App, whose CStart re-enables both around its own initialization
     * (iLLD CStart0.c does this regardless of the SBL's state).
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());

    initLED();      /* decision signalling + safe-mode blink (P00.5) */

    /* 锚定版本串 g_sbl_version：volatile 读是副作用，任何优化级别下都
     * 不可剔除，从而躲过链接期死码消除（-Wl-Oc），产物内 "SBLFW ..." 可检索。 */
    {
        volatile char v0 = g_sbl_version[0];
        (void)v0;
    }

    SBL_boot();     /* never returns */

    return 1;
}
