/*
 * sha512.h - self-contained SHA-512 (FIPS 180-4), no target dependencies.
 *
 * Own implementation instead of mbedTLS so the identical code runs in the
 * host unit tests (coding-plan decision C3); constants generated by
 * tools/gen_crypto_consts.py and re-verified against RFC 8032 vectors.
 */
#ifndef C6_SHA512_H
#define C6_SHA512_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define C6_SHA512_DIGEST_LEN 64u
#define C6_SHA512_BLOCK_LEN  128u

typedef struct
{
    uint64_t h[8];
    uint64_t len_bits;                 /* total message length in bits  */
    uint8_t  buf[C6_SHA512_BLOCK_LEN];
    size_t   buf_len;
} c6_sha512_ctx_t;

void c6_sha512_init(c6_sha512_ctx_t *ctx);
void c6_sha512_update(c6_sha512_ctx_t *ctx, const uint8_t *data, size_t len);
void c6_sha512_final(c6_sha512_ctx_t *ctx, uint8_t out[C6_SHA512_DIGEST_LEN]);

/* one-shot */
void c6_sha512(const uint8_t *data, size_t len, uint8_t out[C6_SHA512_DIGEST_LEN]);

#ifdef __cplusplus
}
#endif

#endif /* C6_SHA512_H */
