/*
 * test_tcfw.c - G-OTA-1: TCFW bundle verifier host tests
 *
 * Vectors from test_vectors.h (generated by tools/gen_test_vectors.py with
 * the dev key pair, same signing rules as esp32c6_car tools/sign_bundle.py).
 */
#include "test.h"

#include "mw/ota/tcfw_bundle.h"
#include "mw/ota/ota_layout.h"
#include "test_vectors.h"

/* collect what the sink saw */
static uint8_t  sinkBuf[TV_APP_LEN];
static uint32_t sinkMax;
static uint32_t sinkCalls;

static int sink(void *arg, uint32_t off, const uint8_t *d, uint32_t n)
{
    (void)arg;
    if (off + n > TV_APP_LEN)
    {
        return 1;
    }
    memcpy(&sinkBuf[off], d, n);
    if (off + n > sinkMax)
    {
        sinkMax = off + n;
    }
    sinkCalls++;
    return 0;
}

static int failSink(void *arg, uint32_t off, const uint8_t *d, uint32_t n)
{
    (void)arg; (void)off; (void)d; (void)n;
    return 1;
}

static void feedAll(TcfwCtx *ctx, const uint8_t *data, uint32_t len)
{
    /* feed in awkward chunk sizes to exercise the header/payload split */
    uint32_t off = 0u;

    while (off < len)
    {
        uint32_t n = 37u;                       /* not a divisor of anything */

        if (off < TCFW_HDR_LEN)
        {
            n = 61u;                            /* cross the header boundary  */
        }
        if (n > (len - off))
        {
            n = len - off;
        }
        (void)TCFW_feed(ctx, &data[off], n, 0, sink);
        off += n;
    }
}

int main(void)
{
    TcfwCtx ctx;
    TcfwState st;

    /* 1. valid bundle verifies, payload streams through the sink intact */
    T_CASE("valid bundle");
    memset(sinkBuf, 0xAA, sizeof(sinkBuf));
    sinkMax = 0u;
    sinkCalls = 0u;
    TCFW_init(&ctx, tv_pub);
    feedAll(&ctx, tv_bundle, TV_BUNDLE_LEN);
    T_CHECK_EQ_I(ctx.state, TCFW_DONE);
    st = TCFW_finish(&ctx);
    T_CHECK_EQ_I(st, TCFW_DONE);
    T_CHECK_EQ_I(sinkMax, TV_APP_LEN);
    T_CHECK(sinkCalls > 1);
    T_CHECK(memcmp(sinkBuf, &tv_bundle[TCFW_HDR_LEN], TV_APP_LEN) == 0);

    /* 2. tampered signed-range byte -> signature rejected at the header,
     *    and NO payload byte reaches the sink afterwards */
    T_CASE("tampered header byte");
    {
        uint8_t bad[200];

        memcpy(bad, tv_bundle, sizeof(bad));
        bad[20] ^= 0x40u;                       /* inside app_sha, in [0,84)*/
        sinkMax = 0u;
        TCFW_init(&ctx, tv_pub);
        st = TCFW_feed(&ctx, bad, sizeof(bad), 0, sink);
        T_CHECK_EQ_I(st, TCFW_ERR_SIG);
        T_CHECK_EQ_I(sinkMax, 0u);
    }

    /* 3. tampered signature itself -> rejected */
    T_CASE("tampered signature");
    {
        uint8_t bad[200];

        memcpy(bad, tv_bundle, sizeof(bad));
        bad[100] ^= 0x01u;                      /* inside the 64B signature */
        TCFW_init(&ctx, tv_pub);
        st = TCFW_feed(&ctx, bad, sizeof(bad), 0, sink);
        T_CHECK_EQ_I(st, TCFW_ERR_SIG);
    }

    /* 4. right bundle, wrong key -> rejected */
    T_CASE("wrong key");
    TCFW_init(&ctx, tv_pub);
    st = TCFW_feed(&ctx, tv_wrongkey, 200u, 0, sink);
    T_CHECK_EQ_I(st, TCFW_ERR_SIG);

    /* 5. tampered payload: header signature still passes (payload is not
     *    signed), the digest check catches it at finish */
    T_CASE("tampered payload");
    {
        uint8_t bad[TV_BUNDLE_LEN];

        memcpy(bad, tv_bundle, sizeof(bad));
        bad[TCFW_HDR_LEN + 12345u] ^= 0x10u;
        TCFW_init(&ctx, tv_pub);
        feedAll(&ctx, bad, sizeof(bad));
        T_CHECK_EQ_I(ctx.state, TCFW_DONE);
        st = TCFW_finish(&ctx);
        T_CHECK_EQ_I(st, TCFW_ERR_HASH);
    }

    /* 6. truncation: stream ends early -> finish reports TRUNCATED */
    T_CASE("truncated bundle");
    TCFW_init(&ctx, tv_pub);
    feedAll(&ctx, tv_bundle, TV_BUNDLE_LEN - 3u);
    T_CHECK_EQ_I(ctx.state, TCFW_APP_DATA);
    st = TCFW_finish(&ctx);
    T_CHECK_EQ_I(st, TCFW_ERR_TRUNCATED);

    /* 7. bad magic */
    T_CASE("bad magic");
    {
        uint8_t bad[16];

        memcpy(bad, tv_bundle, sizeof(bad));
        bad[0] = 'X';
        TCFW_init(&ctx, tv_pub);
        st = TCFW_feed(&ctx, bad, 200u, 0, sink);
        T_CHECK_EQ_I(st, TCFW_ERR_MAGIC);
    }

    /* 8. inconsistent total_len -> size error */
    T_CASE("bad total_len");
    {
        uint8_t bad[16];

        memcpy(bad, tv_bundle, sizeof(bad));
        bad[8] = 0x00u;                          /* total LSB               */
        bad[9] = 0x00u;
        bad[10] = 0x00u;
        bad[11] = 0x00u;
        TCFW_init(&ctx, tv_pub);
        st = TCFW_feed(&ctx, bad, 200u, 0, sink);
        T_CHECK_EQ_I(st, TCFW_ERR_SIZE);
    }

    /* 9. sink failure surfaces as I/O, distinct from size errors */
    T_CASE("sink failure");
    {
        TCFW_init(&ctx, tv_pub);
        st = TCFW_feed(&ctx, tv_bundle, TV_BUNDLE_LEN, 0, failSink);
        T_CHECK_EQ_I(st, TCFW_ERR_IO);
    }

    T_RESULT("test_tcfw");
}
