#!/usr/bin/env python3
"""Generate components/c6_ota/c6_consts.h (SHA-512 + ed25519 constants).

Checked-in generated file: rebuilding the firmware does NOT need Python.
Re-run only to re-audit the constants:

    python tools/gen_crypto_consts.py
"""
import hashlib

from math import isqrt

OUT = "components/c6_ota/c6_consts.h"


def nth_prime(n):
    """n-th prime, n >= 0."""
    count = 0
    cand = 1
    while True:
        cand += 1
        if all(cand % d for d in range(2, isqrt(cand) + 1)):
            if count == n:
                return cand
            count += 1


def _iroot(v, k):
    """Exact floor(v ** (1/k)) by binary search."""
    lo, hi = 0, 1 << ((v.bit_length() // k) + 2)
    while lo < hi:
        mid = (lo + hi + 1) // 2
        if mid ** k <= v:
            lo = mid
        else:
            hi = mid - 1
    return lo


def frac_bits_exact(x, k, bits):
    """floor(frac(x^(1/k)) * 2^bits), all-integer (no float error).

    floor(x^(1/k)*2^bits) - floor(x^(1/k))*2^bits."""
    scaled = _iroot(x << (k * bits), k)
    return scaled - _iroot(x, k) * (1 << bits)


def to_le64(x):
    return [int.from_bytes(x[i:i + 8], "little") for i in range(0, len(x), 8)]


def limbs64(v):
    """32-byte little-endian value -> 8 x uint32 LE limbs (rv32-friendly)."""
    b = v.to_bytes(32, "little")
    return [int.from_bytes(b[i:i + 4], "little") for i in range(0, 32, 4)]


def bytes_def(name, v, width=32):
    b = v.to_bytes(width, "little")
    return "#define %s { %s }" % (name, ", ".join("0x%02xU" % x for x in b))


def limbs_def(name, v):
    return "#define %s { %s }" % (name, ", ".join("0x%08xU" % x for x in limbs64(v)))


def main():
    lines = []
    a = lines.append
    a("/*")
    a(" * c6_consts.h - generated by tools/gen_crypto_consts.py (do not edit)")
    a(" * SHA-512 constants (FIPS 180-4) and ed25519 parameters (RFC 8032).")
    a(" */")
    a("#ifndef C6_CONSTS_H")
    a("#define C6_CONSTS_H")
    a("")
    a("#include <stdint.h>")
    a("")

    k_words = [frac_bits_exact(nth_prime(i), 3, 64) for i in range(80)]
    a("/* SHA-512 round constants K[80] */")
    a("static const uint64_t C6_SHA512_K[80] = {")
    for i in range(0, 80, 2):
        a("    " + " ".join("0x%016xU," % x for x in k_words[i:i + 2]))
    a("};")
    a("")

    h_words = [frac_bits_exact(nth_prime(i), 2, 64) for i in range(8)]
    a("/* SHA-512 initial hash state (fractional sqrt of first 8 primes) */")
    a("static const uint64_t C6_SHA512_IV[8] = {")
    for i in range(0, 8, 2):
        a("    " + " ".join("0x%016xU," % x for x in h_words[i:i + 2]))
    a("};")
    a("")

    p = 2 ** 255 - 19
    d = (-121665 * pow(121666, p - 2, p)) % p
    sqrt_m1 = pow(2, (p - 1) // 4, p)
    order = 2 ** 252 + 27742317777372353535851937790883648493
    by = (4 * pow(5, p - 2, p)) % p
    xx = (by * by - 1) * pow(d * by * by + 1, p - 2, p) % p
    bx = pow(xx, (p + 3) // 8, p)
    if (bx * bx - xx) % p != 0:
        bx = bx * sqrt_m1 % p
    if (bx * bx - xx) % p != 0:
        bx = bx * 2 % p
    if bx % 2 != 0:
        bx = p - bx
    assert (by * by - bx * bx - 1 - d * bx * bx * by * by) % p == 0, "base point sanity failed"

    a("/* ---- ed25519 (RFC 8032), 32-byte values as little-endian byte arrays ---- */")
    a(limbs_def("C6_FE_P", p))
    a("")
    a("/* d = -121665/121666 mod p */")
    a(limbs_def("C6_ED_D", d))
    a("")
    a("/* sqrt(-1) = 2^((p-1)/4) mod p */")
    a(limbs_def("C6_ED_SQRT_M1", sqrt_m1))
    a("")
    a("/* group order L = 2^252 + 27742317777372353535851937790883648493 */")
    a(bytes_def("C6_ED_L", order))
    a("")
    a("/* base point */")
    a(bytes_def("C6_ED_BX", bx))
    a(bytes_def("C6_ED_BY", by))
    a("")
    a("#endif /* C6_CONSTS_H */")

    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(lines) + "\n")

    # ---- self-check ----
    assert h_words[0] == 0x6A09E667F3BCC908, hex(h_words[0])
    assert k_words[0] == 0x428A2F98D728AE22, hex(k_words[0])
    assert k_words[79] == 0x6C44198C4A475817, hex(k_words[79])
    print("ok:", OUT)
    print("sha512('abc') =", hashlib.sha512(b"abc").hexdigest(), "(host test vector)")


if __name__ == "__main__":
    main()
